-- MySQL Script generated by MySQL Workbench
-- Tue Apr 16 14:20:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_library` DEFAULT CHARACTER SET utf8 ;
USE `db_library` ;

-- -----------------------------------------------------
-- Table `db_library`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`gener`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`gener` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`book` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `year` DATE NOT NULL,
  `edition` VARCHAR(45) NOT NULL,
  `id_author` INT NOT NULL,
  `id_gener` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_author_idx` (`id_author` ASC) VISIBLE,
  INDEX `fk_id_gener_idx` (`id_gener` ASC) VISIBLE,
  CONSTRAINT `fk_id_author`
    FOREIGN KEY (`id_author`)
    REFERENCES `db_library`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_gener`
    FOREIGN KEY (`id_gener`)
    REFERENCES `db_library`.`gener` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_library`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_library`.`loan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt_loan` DATE NOT NULL,
  `dt_delivery` DATE NOT NULL,
  `id_user` INT NOT NULL,
  `id_book` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_id_book_idx` (`id_book` ASC) VISIBLE,
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_library`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `db_library`.`book` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
